# Generated by Django 4.2.7 on 2023-12-07 08:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("livestream_signs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="room",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
