# Generated by Django 4.2.7 on 2023-12-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("livestream_signs", "0002_remove_message_room_delete_chatroom_delete_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
            ],
        ),
    ]
