# Generated by Django 4.2.7 on 2023-12-18 16:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livestream_signs", "0005_userprofile_delete_temporaryuser"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
